'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Aone.Id_Oprek_Tools.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property adb() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("adb", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AdbWinApi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AdbWinApi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property AdbWinUsbApi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AdbWinUsbApi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''title Cek Slot
        '''fastboot getvar all
        '''pause
        '''exit.
        '''</summary>
        Friend ReadOnly Property CheckActiveSlot() As String
            Get
                Return ResourceManager.GetString("CheckActiveSlot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''title Checking Connection
        '''fastboot devices
        '''adb devices
        '''.
        '''</summary>
        Friend ReadOnly Property DeviceCheck() As String
            Get
                Return ResourceManager.GetString("DeviceCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property fastboot() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fastboot", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''title Dmesg
        '''adb shell su -c dmesg .
        '''</summary>
        Friend ReadOnly Property GetDmesg() As String
            Get
                Return ResourceManager.GetString("GetDmesg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''title Ghatering Information
        '''fastboot getvar all 
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property GetInformationBootloader() As String
            Get
                Return ResourceManager.GetString("GetInformationBootloader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''title Ghatering Information
        '''adb shell getprop
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property GetInformationSystem() As String
            Get
                Return ResourceManager.GetString("GetInformationSystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''title logcat
        '''adb logcat.
        '''</summary>
        Friend ReadOnly Property Getlogcat() As String
            Get
                Return ResourceManager.GetString("Getlogcat", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
